### ISSUE TITLE
How do you see vendors cookbook management with librarian-chef

### ISSUE THREAD

**Issue by gansbrest** [applicationsonline/librarian-chef#5]
Since librarian-chef doesn't create real repos for installed 3rd party cookbooks it could be hard to keep track of changes, because there is a need to modify community book from time to time. 

It there would be real git repo for each cookbook then by doing git status it would be easy to spot local modifications and compare them with latest master from github.

I'm curious to know how you see 3rd party cookbook management including pull request creation with some useful features by keeping uncommited cookboks in the /cookbooks folder.

**Comment by yfeldblum** [comment]
Librarian-Chef has no support for forking and testing cookbooks because you can do that with separate tools. It is typically expected to use the repository-per-cookbook pattern for forked cookbooks and to test the forked cookbooks separately, and you can use Librarian-Chef to pull in the forks into your main Chef-repo.
